import { FAQ_TR, FAQ_EN } from "@/lib/seo";

export type Locale = "tr" | "en";
export interface LandingContent {
  locale: Locale; path: string;
  nav: { modules: string; agent: string; governance: string; pricing: string; login: string; cta: string; otherLang: string; otherLangPath: string; menu: string; skip: string };
  hero: { eyebrow: string; title1: string; title2: string; lede: string; ctaPrimary: string; ctaSecondary: string; note: string; caption: string };
  intro: { title: string; p: string; items: { t: string; d: string }[] };
  modules: { label: string; h2: string; p: string; items: { t: string; s: string; d: string; title: string; tags: string[] }[] };
  demo: { label: string; period: string; branch: string; source: string; observed: string; projection: string; year: string; development: string; paid: string; outstanding: string; claim: string; selection: string; triangle: string; pattern: string; curve: string; nominal: string; discounted: string; note: string; summary: string; status: string[] };
  agent: { label: string; h2: string; p: string; prompt: string; example: string; reply: string; steps: string[]; footnote: string; features: string[]; tools: { m: string; d: string }[] };
  governance: { label: string; h2: string; p: string; items: { t: string; d: string }[] };
  enterprise: { label: string; title: string; p: string; cloud: string; local: string; database: string; model: string; private: string; cta: string };
  pricing: { label: string; h2: string; p: string; recommended: string; plans: { n: string; p: string; s: string; d: string; f: string[]; h: string; a: string; on?: boolean }[] };
  faq: { h2: string; p: string; items: { q: string; a: string }[] };
  contact: { label: string; h2: string; p: string; name: string; email: string; company: string; optional: string; message: string; placeholder: string; submit: string; sending: string; okTitle: string; okBody: string; again: string; note: string; genericError: string };
  footer: { tagline: string; privacy: string; terms: string; contact: string; rights: string };
}

export const TR: LandingContent = {
  locale: "tr", path: "/",
  nav: { modules: "Platform", agent: "AI Agent", governance: "Kurumsal", pricing: "Planlar", login: "Giriş yap", cta: "Ücretsiz başla", otherLang: "EN", otherLangPath: "/en", menu: "Menü", skip: "İçeriğe geç" },
  hero: { eyebrow: "AI destekli aktüeryal çalışma alanı", title1: "Veriden karara.", title2: "Tek bir platform.", lede: "Veriyi bağlayın, modellerinizi oluşturun, sonuçların arkasını görün. Rezervden nakit akışına, tüm süreç AI Agent ile aynı çalışma alanında.", ctaPrimary: "Ücretsiz başlayın", ctaSecondary: "Platformu keşfedin", note: "Kredi kartı gerekmez. Excel veya CSV ile başlayın.", caption: "Geçmişi anlayın. Geleceği modelleyin." },
  intro: { title: "Daha az dosya trafiği.\nDaha fazla içgörü.", p: "Aktüeryal işin değeri, dosyaları birleştirmekte değil; ne söylediklerini anlamakta. Actuarius, veri ile model arasındaki mesafeyi kapatır.", items: [{ t: "Bağlantılı veri", d: "Hasar, prim ve üçgenler aynı dönem bağlamında." }, { t: "Görünür varsayımlar", d: "Faktörden nihai hasara, modelin mantığı elinizin altında." }, { t: "Odaklı analiz", d: "Sonuçtan kaynak dosyaya kadar inen bir bakış." }] },
  modules: {
    label: "Bütün süreç. Ortak bir dil.", h2: "Birbirinden kopuk araçlar değil,\nbağlantılı bir iş akışı.", p: "Veriyi bir kez hazırlayın. Rezerv, ödeme deseni ve iskonto çalışmalarını aynı platformda ilerletin.",
    items: [
      { t: "Veri", s: "Hazırlayın", title: "Sağlam bir model,\nanlaşılır veriyle başlar.", d: "Hasar ve prim dosyalarını içe aktarın, alanları eşleştirin ve dönemleri düzenleyin. Hazır üçgenlerle ya da dosya bazlı veriyle çalışın.", tags: ["Excel / CSV", "Alan eşleştirme", "Dönem yönetimi"] },
      { t: "Rezerv", s: "Modelleyin", title: "Sadece sonucu değil,\nnedenini de görün.", d: "Gelişim faktörlerini inceleyin, aykırı hücreleri değerlendirin. Chain-Ladder ve BF seçimlerini kaza dönemi bazında yönetin.", tags: ["Chain-Ladder & BF", "LDF & kuyruk", "Dosya analizi"] },
      { t: "Nakit Akışı", s: "Projeksiyon yapın", title: "Rezervin zaman\niçindeki karşılığı.", d: "Ödeme gelişiminden desen oluşturun. Çeyreklik veya aylık nakit akışlarıyla gelecekteki ödeme dağılımını analiz edin.", tags: ["Ödeme deseni", "Aylık / çeyreklik", "LDF seçimi"] },
      { t: "İskonto", s: "Değerleyin", title: "Gelecek ödemeleri\nbugünün değeriyle okuyun.", d: "Getiri eğrisi, illikidite primi ve risk marjı varsayımlarıyla gerçekleşmiş hasar yükümlülüğünü değerlendirin.", tags: ["IFRS 17 LIC", "Getiri eğrisi", "Risk marjı"] },
    ],
  },
  demo: { label: "Temsili ürün akışı", period: "Değerleme", branch: "Branş", source: "Hasar verisi", observed: "Gözlenen", projection: "Projeksiyon", year: "Kaza yılı", development: "Gelişim dönemi", paid: "Ödenen", outstanding: "Muallak", claim: "Dosya no", selection: "Seçili LDF", triangle: "Gelişim üçgeni", pattern: "Ödeme deseni", curve: "Getiri eğrisi", nominal: "Nominal", discounted: "İskontolu", note: "Gösterim amaçlı örnek veriler. Gerçek hesaplama değildir.", summary: "Veri → Model → Karar", status: ["Veri hazır", "Model çalışma alanı", "Ödeme projeksiyonu", "Değerleme görünümü"] },
  agent: {
    label: "Actuarius AI Agent", h2: "Siz yönü belirleyin.\nAgent modelde çalışsın.", p: "Sohbetin ötesinde, modelinizle çalışan bir asistan. İsteğinizi aktüeryal araçlara dönüştürür; uygulanan değişiklikleri aynı arayüzde takip edersiniz.", prompt: "Fire & Home verileri hazır. Üçgeni oluştur, gelişim faktörlerini incele ve rezerv modelini hazırla.", example: "Örnek agent senaryosu", reply: "Model akışını hazırladım. İncelemeniz için adımları özetliyorum:", steps: ["Dönem ve branş verisi modele bağlandı", "Gelişim faktörleri ve aykırı hücreler incelendi", "CL / BF varsayımları değerlendirmeye hazır"], footnote: "Temsili senaryo · Aktüeryal değerlendirme ve nihai karar sizde.", features: ["Doğal dille model yönetimi", "Arayüzde görünür işlemler", "İstediğiniz anda manuel kontrol"], tools: [{ m: "Rezerv", d: "Üçgen, LDF, hücre eleme, kuyruk ve BF varsayımları" }, { m: "Nakit Akışı", d: "Ödeme deseni ve gelişim faktörleri" }, { m: "İskonto", d: "Varsayımlar ve LIC hesabı" }, { m: "Veri", d: "Veri durumu ve modüller arası geçiş" }],
  },
  governance: { label: "Kontrol sizde kalır", h2: "Güçlü modeller.\nAçık bir karar izi.", p: "Varsayımı sonuçtan ayırmadan çalışın. Kurumsal sürümde erişim, model kilidi ve denetim kayıtlarıyla ekip sürecini yönetin.", items: [{ t: "Senaryo versiyonları", d: "Farklı varsayımları ayrı modellerde değerlendirin." }, { t: "Model kilidi", d: "Kurumsal ekipte eşzamanlı düzenleme çakışmalarını önleyin." }, { t: "Denetim kayıtları", d: "Kurumsal değişiklikleri kullanıcı ve model bağlamında izleyin." }] },
  enterprise: { label: "Actuarius Enterprise", title: "Sizin altyapınız.\nSizin çalışma biçiminiz.", p: "Masaüstü deneyimi, Oracle veri bağlantısı ve kurum içi kurulum. Yerel veya kurumunuzun seçtiği uyumlu LLM uç noktasıyla agent kullanımını yapılandırın.", cloud: "Web üzerinden başlayın", local: "Kurum içi çalışma alanı", database: "Oracle veri katmanı", model: "Yapılandırılabilir AI", private: "Kuruma özel kurulum", cta: "Kurumsal demoyu planlayın" },
  pricing: { label: "İhtiyacınıza göre büyür", h2: "Küçük başlayın.\nBirlikte ölçekleyin.", p: "İlk modelinizden kurumsal çalışma alanınıza.", recommended: "Tüm analiz akışı", plans: [
    { n: "Free", p: "₺0", s: "kalıcı", d: "İlk modelinizi oluşturun.", f: ["1 dönem · 1 branş", "Rezerv modülü", "AI Agent", "Excel çıktısı"], h: "/reserve", a: "Ücretsiz başlayın" },
    { n: "Pro", p: "₺100", s: "/ ay", d: "Analiz alanınızı genişletin.", f: ["Sınırsız dönem ve branş", "Nakit akışı ve iskonto", "Senaryo versiyonları", "Tüm modüllerde AI Agent"], h: "/onboarding/plan", a: "Pro'ya geçin", on: true },
    { n: "Enterprise", p: "Size özel", s: "", d: "Ekibiniz ve altyapınız için.", f: ["Çoklu kullanıcı ve roller", "Oracle entegrasyonu", "Kurumsal denetim kayıtları", "Kurum içi kurulum"], h: "#contact", a: "Birlikte değerlendirelim" },
  ] },
  faq: { h2: "Aklınızdaki\nsorular.", p: "Daha fazlasını konuşmak için bize ulaşın.", items: FAQ_TR },
  contact: { label: "Birlikte bakalım", h2: "Bir sonraki modeliniz,\nyeni bir başlangıç olsun.", p: "Mevcut sürecinizi anlatın. Ekibinize uygun çalışma alanını birlikte değerlendirelim.", name: "Ad soyad", email: "İş e-postası", company: "Şirket", optional: "isteğe bağlı", message: "Size nasıl yardımcı olabiliriz?", placeholder: "Ekibinizi ve üzerinde çalıştığınız süreci kısaca anlatın…", submit: "Görüşme talebi gönder", sending: "Gönderiliyor…", okTitle: "Mesajınız bize ulaştı.", okBody: "{to} adresinden sizinle iletişime geçeceğiz.", again: "Yeni mesaj gönder", note: "Doğrudan yazmak isterseniz", genericError: "Mesaj gönderilemedi. Lütfen tekrar deneyin." },
  footer: { tagline: "Aktüeryal işin bağlantılı hali.", privacy: "Gizlilik", terms: "Kullanım şartları", contact: "İletişim", rights: "Tüm hakları saklıdır." },
};

export const EN: LandingContent = {
  locale: "en", path: "/en",
  nav: { modules: "Platform", agent: "AI Agent", governance: "Enterprise", pricing: "Plans", login: "Sign in", cta: "Start free", otherLang: "TR", otherLangPath: "/", menu: "Menu", skip: "Skip to content" },
  hero: { eyebrow: "The AI-powered actuarial workspace", title1: "From data to decision.", title2: "One connected platform.", lede: "Connect your data, build your models, understand the results. From reserving to cash flow, bring your workflow together with an AI agent.", ctaPrimary: "Start for free", ctaSecondary: "Explore the platform", note: "No credit card required. Start with Excel or CSV.", caption: "Understand the past. Model what comes next." },
  intro: { title: "Less file juggling.\nMore insight.", p: "The value of actuarial work is in understanding the data, not moving it between files. Actuarius brings your data and models closer together.", items: [{ t: "Connected data", d: "Claims, premiums and triangles in one period context." }, { t: "Visible assumptions", d: "From development factors to ultimate loss, the logic stays in view." }, { t: "Focused analysis", d: "Follow a result all the way to the underlying claim." }] },
  modules: { label: "One workflow. A shared language.", h2: "Not a collection of tools.\nA connected way to work.", p: "Prepare your data once. Develop your reserve, payment pattern and discounting analysis on the same platform.", items: [
    { t: "Data", s: "Prepare", title: "A sound model starts\nwith clear data.", d: "Import claim and premium files, map fields and organise valuation periods. Work with claim-level data or ready-made triangles.", tags: ["Excel / CSV", "Field mapping", "Valuation periods"] },
    { t: "Reserving", s: "Model", title: "See the result.\nUnderstand the reasoning.", d: "Explore development factors and evaluate outliers. Manage Chain-Ladder and BF selections by accident period.", tags: ["Chain-Ladder & BF", "LDF & tail", "Claim-level analysis"] },
    { t: "Cash Flow", s: "Project", title: "Your reserve,\nwith a time dimension.", d: "Build a pattern from payment development. Analyse future payments with quarterly or monthly cash flow projections.", tags: ["Payment patterns", "Monthly / quarterly", "LDF selection"] },
    { t: "Discounting", s: "Value", title: "Future payments.\nPresent-day value.", d: "Evaluate the liability for incurred claims using yield curve, illiquidity premium and risk adjustment assumptions.", tags: ["IFRS 17 LIC", "Yield curves", "Risk adjustment"] },
  ] },
  demo: { label: "Illustrative product flow", period: "Valuation", branch: "Line of business", source: "Claims data", observed: "Observed", projection: "Projected", year: "Accident year", development: "Development period", paid: "Paid", outstanding: "Outstanding", claim: "Claim ID", selection: "Selected LDF", triangle: "Development triangle", pattern: "Payment pattern", curve: "Yield curve", nominal: "Nominal", discounted: "Discounted", note: "Illustrative sample data, not an actual calculation.", summary: "Data → Model → Decision", status: ["Data ready", "Model workspace", "Payment projection", "Valuation view"] },
  agent: { label: "Actuarius AI Agent", h2: "You set the direction.\nYour agent works the model.", p: "An assistant that goes beyond conversation. It turns your request into actuarial tool actions, with changes visible in the same workspace.", prompt: "The Fire & Home data is ready. Build the triangle, review development factors and prepare the reserve model.", example: "Example agent scenario", reply: "The model workflow is prepared. Here are the steps for your review:", steps: ["Period and line-of-business data connected", "Development factors and outliers reviewed", "CL / BF assumptions ready for assessment"], footnote: "Illustrative scenario · Actuarial judgement and the final decision remain yours.", features: ["Model management in natural language", "Actions visible in the interface", "Manual control whenever you need it"], tools: [{ m: "Reserving", d: "Triangles, LDFs, exclusions, tails and BF assumptions" }, { m: "Cash Flow", d: "Payment patterns and development factors" }, { m: "Discounting", d: "Assumptions and LIC calculation" }, { m: "Data", d: "Data status and navigation between modules" }] },
  governance: { label: "Stay in control", h2: "Powerful models.\nA clear decision trail.", p: "Keep assumptions close to their results. The enterprise edition adds access controls, model locks and audit records for team workflows.", items: [{ t: "Scenario versions", d: "Evaluate different assumptions in separate model versions." }, { t: "Model locks", d: "Prevent conflicting edits across your enterprise team." }, { t: "Audit records", d: "Track enterprise changes in their user and model context." }] },
  enterprise: { label: "Actuarius Enterprise", title: "Your infrastructure.\nYour way of working.", p: "A desktop experience, Oracle data connectivity and on-premise deployment. Configure the agent with a local or organisation-selected compatible LLM endpoint.", cloud: "Start on the web", local: "Your enterprise workspace", database: "Oracle data layer", model: "Configurable AI", private: "Organisation-specific setup", cta: "Plan an enterprise demo" },
  pricing: { label: "Room to grow", h2: "Start small.\nScale together.", p: "From your first model to a team-wide workspace.", recommended: "The complete analysis flow", plans: [
    { n: "Free", p: "₺0", s: "forever", d: "Build your first model.", f: ["1 period · 1 line of business", "Reserving module", "AI Agent", "Excel export"], h: "/reserve", a: "Start for free" },
    { n: "Pro", p: "₺100", s: "/ month", d: "Extend your analysis.", f: ["Unlimited periods and lines", "Cash flow and discounting", "Scenario versions", "AI Agent across modules"], h: "/onboarding/plan", a: "Go Pro", on: true },
    { n: "Enterprise", p: "Tailored", s: "", d: "For your team and infrastructure.", f: ["Multiple users and roles", "Oracle integration", "Enterprise audit records", "On-premise deployment"], h: "#contact", a: "Let’s talk" },
  ] },
  faq: { h2: "Good\nquestions.", p: "Get in touch if you would like to know more.", items: FAQ_EN },
  contact: { label: "Let’s take a look", h2: "Your next model.\nA new way forward.", p: "Tell us about your process. Let’s explore the right workspace for your team.", name: "Full name", email: "Work email", company: "Company", optional: "optional", message: "How can we help?", placeholder: "Tell us a little about your team and workflow…", submit: "Request a conversation", sending: "Sending…", okTitle: "Your message is in.", okBody: "We will be in touch at {to}.", again: "Send another message", note: "Prefer to email us?", genericError: "Your message could not be sent. Please try again." },
  footer: { tagline: "Actuarial work, connected.", privacy: "Privacy", terms: "Terms of use", contact: "Contact", rights: "All rights reserved." },
};
